### ISSUE TITLE
`switch` with non-constant cases

### ISSUE THREAD

**Issue by emilaxelsson** [Feldspar/feldspar-language#141]
The following generates invalid C code:

```
> icompile $ \a -> switch (123 :: Data Double) [(a+1,234)] (a :: Data Index)
void test(uint32_t v0, double * out)
{
  switch (v0)
  {
    case (v0 + 1):
      *out = 234.0;
      break;
    default:
      *out = 123.0;
      break;
  }
}
```

I think the type for `switch` should be changed from

    switch :: (Syntax a, Eq (Internal a), Syntax b) => b -> [(a, b)] -> a -> b

to

    switch :: (Syntax a, Eq (Internal a), Syntax b) => b -> [(Internal a, b)] -> a -> b

to ensure that the domain of the mapping only has constant values.

**Comment by emwap** [comment]
:+1:
